name = "A0craft"
author = "A0"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6351271f102141d60fcff11393134ed35d4bc9d13c877a7cb03d79d97dae2bb6"

[versions]
fabric = "0.19.5"
minecraft = "26.2"
