name = "A0craft"
author = "A0"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ff150ff63834830fc1321eddb6e6c79b05e6abf2f61b38c86d931684f69b5259"

[versions]
fabric = "0.19.5"
minecraft = "26.3"
