name = "A0craft"
author = "A0"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d483d7fa82101d355ed6fe3d7e2ff9a37208cde9a35f76c21c9d924eb893d5f6"

[versions]
fabric = "0.19.5"
minecraft = "26.3"
